# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-28 19:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_team',
            old_name='team',
            new_name='team_id',
        ),
        migrations.RenameField(
            model_name='user_team',
            old_name='user',
            new_name='user_id',
        ),
    ]
